mt/mt/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('spending.urls')),
]

mt/spending/urls.py
from django.conf.urls import url
from django.views.generic.base import TemplateView

from . import views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='spending/index.html')),
    url(r'^add_category/$', views.CategoryListView.as_view(), name="add-category"),
    url(r'^add_note/$', views.NoteListView.as_view(), name="add-note"),
    url(r'^add_place/$', views.PlaceListView.as_view(), name="add-place"),
    url(r'^add_spending/$', views.SpendingListView.as_view(), name="add-spending"),

    url(r'^list_category/$', views.CategoryListView.as_view(), name="list-category"),
    url(r'^list_note/$', views.NoteListView.as_view(), name="list-note"),
    url(r'^list_place/$', views.PlaceListView.as_view(), name="list-place"),
    url(r'^list_spending/$', views.SpendingListView.as_view(), name="list-spending"),
]

mt/spending/models.py
# from django.contrib.gis.db import models
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(blank=True, default=u'', max_length=255)

    # objects = models.GeoManager()

    def __str__(self):
        return "%s" % self.name


class Note(models.Model):
    """
    Note about something, like a place you ate at
    """
    timestamp = models.DateTimeField('date taken', blank=True, null=True)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, default=u'')
    user = models.ForeignKey(User)

    # objects = models.GeoManager()

    def save(self, *args, **kwargs):
        if not self.id:
            self.timestamp = timezone.now()
        super(Note, self).save(*args, **kwargs)

    def __str__(self):
        return "%s" % self.name


class Place(models.Model):
    """
    decimal  decimal     distance
    places   degrees    (in meters)
    -------  ---------  -----------
      1      0.1000000  11,057.43      11 km
      2      0.0100000   1,105.74       1 km
      3      0.0010000     110.57
      4      0.0001000      11.06
      5      0.0000100       1.11
      6      0.0000010       0.11      11 cm
      7      0.0000001       0.01       1 cm

    -- https://stackoverflow.com/a/16743805

    Latitude in degrees is -90 and +90
    Longitude is in the range -180 and +180

    1+2+1+7 == 11
    1+3+1+7 == 12
    """
    name = models.CharField(max_length=255)
    # Geos Libraries are a nightmare to install
    # removing them until better OS package support is available
    # location = models.PointField(blank=True, null=True)
    lng = models.DecimalField(max_digits=12, decimal_places=7, blank=True, null=True)
    lat = models.DecimalField(max_digits=12, decimal_places=7, blank=True, null=True)
    notes = models.ManyToManyField(Note, blank=True)
    categories = models.ManyToManyField(Category, blank=True)
    # objects = models.GeoManager()

    def __str__(self):
        return "%s" % self.name


class Spending(models.Model):
    timestamp = models.DateTimeField('date published')
    time_of_purchase = models.DateTimeField(blank=True, null=True)
    amount = models.DecimalField(max_digits=19, decimal_places=4)
    description = models.TextField(blank=True, default=u'')
    receipt = models.ImageField(blank=True, null=True)  # upload_to=None
    receipt_text = models.TextField(blank=True,
                                    default=u'')  # Populated via OCR
    place = models.ForeignKey(Place, blank=True, null=True)
    user = models.ForeignKey(User)

    # objects = models.GeoManager()

    def save(self, *args, **kwargs):
        if not self.id:
            self.timestamp = timezone.now()
        super(Spending, self).save(*args, **kwargs)

    def __str__(self):
        return "%s" % self.amount

mt/spending/forms.py
from django.forms import ModelForm

from . import models

class SpendingForm(ModelForm):
    class Meta:
        model = models.Transaction
        fields = ['amount', 'notes', 'type', 'category', 'tag']

mt/spending/views.py
from rest_framework import generics
from rest_framework import renderers

from . import models, serializers


class CategoryListView(generics.ListCreateAPIView):
    queryset = models.Category.objects.all()
    serializer_class = serializers.CategorySerializer
    renderer_classes = (renderers.TemplateHTMLRenderer,renderers.JSONRenderer)

    def list(request, *args, **kwargs):
        pass

    def create(request, *args, **kwargs):
        pass

class CategoryDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = models.Category.objects.all()
    serializer_class = serializers.CategorySerializer
    renderer_classes = (renderers.TemplateHTMLRenderer,renderers.JSONRenderer)

    def retrieve(request, *args, **kwargs):
        pass

    def update(request, *args, **kwargs):
        pass

    def partial_update(request, *args, **kwargs):
        pass

    def destroy(request, *args, **kwargs):
        pass

class NoteListView(generics.ListCreateAPIView):
    queryset = models.Note.objects.all()
    serializer_class = serializers.NoteSerializer
    renderer_classes = (renderers.TemplateHTMLRenderer,renderers.JSONRenderer)

    def list(request, *args, **kwargs):
        pass

    def create(request, *args, **kwargs):
        pass

class NoteDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = models.Note.objects.all()
    serializer_class = serializers.NoteSerializer
    renderer_classes = (renderers.TemplateHTMLRenderer,renderers.JSONRenderer)

    def retrieve(request, *args, **kwargs):
        pass

    def update(request, *args, **kwargs):
        pass

    def partial_update(request, *args, **kwargs):
        pass

    def destroy(request, *args, **kwargs):
        pass

class PlaceListView(generics.CreateAPIView):
    queryset = models.Place.objects.all()
    serializer_class = serializers.PlaceSerializer
    renderer_classes = (renderers.TemplateHTMLRenderer,renderers.JSONRenderer)

    def list(request, *args, **kwargs):
        pass

    def create(request, *args, **kwargs):
        pass

class PlaceDetailView(generics.ListCreateAPIView):
    queryset = models.Place.objects.all()
    serializer_class = serializers.PlaceSerializer
    renderer_classes = (renderers.TemplateHTMLRenderer,renderers.JSONRenderer)

    def retrieve(request, *args, **kwargs):
        pass

    def update(request, *args, **kwargs):
        pass

    def partial_update(request, *args, **kwargs):
        pass

    def destroy(request, *args, **kwargs):
        pass

class SpendingListView(generics.CreateAPIView):
    queryset = models.Spending.objects.all()
    serializer_class = serializers.SpendingSerializer
    renderer_classes = (renderers.TemplateHTMLRenderer,renderers.JSONRenderer)

    def list(request, *args, **kwargs):
        pass

    def create(request, *args, **kwargs):
        pass

class SpendingDetailView(generics.ListCreateAPIView):
    queryset = models.Spending.objects.all()
    serializer_class = serializers.SpendingSerializer
    renderer_classes = (renderers.TemplateHTMLRenderer,renderers.JSONRenderer)

    def retrieve(request, *args, **kwargs):
        pass

    def update(request, *args, **kwargs):
        pass

    def partial_update(request, *args, **kwargs):
        pass

    def destroy(request, *args, **kwargs):
        pass

mt/spending/templates/spending/backbone.html
<script src="//cdnjs.cloudflare.com/ajax/libs/backbone.js/1.2.3/backbone-min.js"></script>
<script>
if(typeof(Backbone) === 'undefined') {
    document.write('<script src="lib/backbone/backbone.js"><\/script>');
}
</script>

mt/spending/templates/spending/index.html
{% extends 'mt/base.html' %}
{% load static %}
{% block head %}

<style>
#map {
    height: 400px;
    width: 100%;
}
</style>
{% endblock %}

{% block main %}
<div id="log-spending-page"></div>
<div id="log-place-page"></div>
<div id="log-note-page"></div>
<div id="log-category-page"></div>

<ul class="add-links">
    <li>
        <a href="#log-place-page">Add Place</a>
    </li>
</ul>

{% endblock %}

{% block js %}
{{ block.super }}



<script type="text/html" id="tmpl-add-spending-form">
    <form id="add-spending">
        <input id="id_timestamp" name="timestamp" type="datetime-local">
        <input id="id_amount" name="amount" type="number" placeholder="1.0" step="0.01" min="0">
        <textarea id="id_description" name="description"></textarea>
        <input id="id_receipt" name="receipt" type="file">
        <textarea id="id_receipt_text" name="receipt_text"></textarea>
        <input id="id_place" name="place" type="hidden">
    </form>
</script>

<script type="text/html" id="tmpl-add-place-form">
    <form id="add-place">
        <input id="id_name" name="name" type="text">
        <div id="map"></div>
        <input id="id_lat" name="lat" type="hidden" value="">
        <input id="id_lng" name="lng" type="hidden" value="">
        <input id="id_notes" name="notes" type="hidden">
        <input id="id_categories" name="categories" type="hidden">
    </form>
</script>

<script type="text/html" id="tmpl-note-form">
    <form id="add-note">
        <input id="id_timestamp" name="timestamp" type="datetime-local">
        <input id="id_name" name="name" type="text">
        <textarea id="id_description" name="description"></textarea>
    </form>
</script>

<script type="text/html" id="tmpl-category-form">
    <form id="add-category">
        <input id="id_name" name="name" type="text">
    </form>
</script>

<script>

var app = window.app = {
    url: {
        add: {
            category: "{% url 'add-category' %}",
            note: "{% url 'add-note' %}",
            place: "{% url 'add-place' %}",
            spending: "{% url 'add-spending' %}"
        },
        list: {
            category: "{% url 'list-category' %}",
            note: "{% url 'list-note' %}",
            place: "{% url 'list-place' %}",
            spending: "{% url 'list-spending' %}"
        }
    },
    templates: {
        add_spending_form: $('#tmpl-add-spending-form').html(),
        add_place_form: $('#tmpl-add-place-form').html(),
        add_note_form: $('#tmpl-note-form').html(),
        add_category_form: $('#tmpl-category-form').html(),
    },
    pages: {
        $spending: $('log-spending-page'),
        $place: $('log-place-page'),
        $note: $('log-note-page'),
        $category: $('log-category-page')
    },
    map: {
        selector: ['#map'],
        map: undefined,
        markers: []
    },
    loaded: {
        doc: false,
        map: false
    }
}

$('.add-links li').on('click', 'a', function(e) {
    e.preventDefault();
    let page_name = $(this).attr('href').split('-')[1];
    let tmpl = app.templates['add_'+page_name+'_form'];
    let page = app.pages['$'+page_name];

    debugger;
    console.log(tmpl);
    page.html(tmpl);
    console.log(page);
});

function initMap(position) {
    app.map.map = new google.maps.Map(document.querySelector(app.map.selector[0]), {
        zoom: 20,
        center: position
    });
    app.map.markers.push(new google.maps.Marker({
            position: position,
            map: map
        })
    );
}

function google_maps_ready(e) {
    app.loaded.map = true;
    $(document).trigger('loaded:map');
}

$(document).ready(function() {
    app.loaded.doc = true;
    $(document).trigger('loaded:doc');
});


$('#get-geo-location').on('click', function(e) {
    navigator.geolocation.getCurrentPosition(function(position) {
        var position = {
            lat: position.coords.latitude,
            lng: position.coords.longitude
        };
    });
});

// $('#add-list').on('click', function(e) {
// 	e.preventDefaults();
// 	console.log("TODO add stuff");
// });

// $('#list-list').on('click', function(e) {
// 	e.preventDefaults();
// 	console.log("TODO click stuff");
// })
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBvVHQ8l3FnP9EpbZEktdh7uwGtw2dTziE&callback=google_maps_ready"></script>

{% endblock %}

mt/spending/templates/spending/jquery.html
<script src="//code.jquery.com/jquery-2.1.4.min.js"></script>
<script>window.jQuery || document.write('<script src="lib/jquery/jquery-2.1.4.js"><\/script>');</script>

mt/spending/templates/spending/underscore.html
<script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
<script>
if(typeof(_) === 'undefined') {
    document.write('<script src="lib/underscore/underscore.js"><\/script>');
}
</script>